student:
    resource: "@StudentBundle/Controller/"
    type:     annotation
    prefix:   /

root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /students/random
        permanent: true